tabWidth              = 2
semi                  = false
plugins               = ["prettier-plugin-tailwindcss", "prettier-plugin-astro"]
experimentalTernaries = true

overrides           = [{ files = "**.astro", options = { parser = "astro" } }]
astroAllowShorthand = true
